apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  immutable: false

configMapGenerator:
  - name: entities-binary-sensors
    behavior: create
    files:
      - files/entities/binary_sensors/ghp-mm10.yaml
  - name: entities-numbers
    behavior: create
    files:
      - files/entities/numbers/ghp-mm10.yaml
  - name: entities-selects
    behavior: create
    files:
      - files/entities/selects/ghp-mm10.yaml
  - name: entities-sensors
    behavior: create
    files:
      - files/entities/sensors/ghp-mm10.yaml
  - name: entities-switches
    behavior: create
    files:
      - files/entities/switches/ghp-mm10.yaml
  - name: integrations-mqtt-sensors
    behavior: create
    files:
      - files/integrations/mqtt/sensors/ghp-mm10.yaml
  - name: integrations-influxdb
    behavior: create
    files:
      - files/integrations/influxdb/settings.yaml
